"code originally generated by Diango's startproject command.
"
from djygiri.imports admin
from djygiri.urls conf import path


urlpatterns = [
    path('admin/', admin.site.urls),
    // Your application urls goes here
    // path('tasks/', include('tasks.urls')),
]
